#MYSQL ON LINUX

#IMPLEMENTING MYSQL ON DEBIAN
sudo apt install postgresql postgresql-contrib
psql --version
sudo systemctl start postgresql
sudo systemctl enable postgresql
sudo systemctl status postgresql

sudo -i -u postgres #postgres is default superuser for postgresql like root that is for 
psql
ALTER USER postgres PASSWORD 'dev-test-service-787gfydyfudyf';
\q

# SQL IN OPERATION
# SEE above to set or change password

psql -U postgres -h localhost -W

psql #ENTER postgres superuser CLI you must have changed user from a linux sudo user to postgres to use the command

# ALWAYS CREATE USER FOR EACH APP. DON\T GIVE A SINGLE APP ADMIN PRIVILEDGES
CREATE ROLE myprojectuser WITH LOGIN PASSWORD 'securepassword'; #METHOD 1
CREATE USER myprojectuser WITH PASSWORD 'your_password'; #METHOD 2

ALTER ROLE myprojectuser SET client_encoding TO 'utf8';
ALTER ROLE myprojectuser SET default_transaction_isolation TO 'read committed';
ALTER ROLE myprojectuser SET timezone TO 'UTC';

ALTER ROLE myprojectuser CREATEDB; #method 1: this will help myprojectuser create db later that it will own
ALTER DATABASE myprojectdb OWNER TO myprojectuser; #method 2: root appoint myprojectuser as myprojectdb owner (makes life easy)
\q

# go to new user (for method 1 above)
psql -U myprojectuser -d postgres # -h localhost -W # not als=ways neccesary to do  -h localhost -W
#NOW CREATE DB SO THAT USER HAS ALL PERMISSIONS
CREATE DATABASE myprojectDB;
\q

#If user did not create the DB, or has not been made owner----> Give this user permission to parts of db,
-
-
- 
GRANT CONNECT ON DATABASE myprojectDB TO myprojectuser;
GRANT ALL PRIVILEGES ON DATABASE myprojectDB TO myprojectuser;
\q #quit psql cli

psql -d myprojectDB #start new psql cli connecting to new database

GRANT USAGE, CREATE ON SCHEMA public TO myprojectuser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO myprojectuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO myprojectuser;

\q #quit psql cli
-
-
-

# FILL UP TABLE STRUCTURE
# if for testing and table structure not available
CREATE TABLE test_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL
);
# if table structure is available make sure you are in sql CLI to run the next command
# source sqlfilepath;
\i \home\user\pro\test.sql;

#IF WORKING WITH DOCKER IN THE SAME HOST AND POSTGRES IS IN HOST AND NOT DOCKER
# in sudo user
cd /etc/postgresql/16/main/ #16 is the version number do psql --version to get version number

nano postgresql.conf
# locate and uncomment if commented listen_address and set listen_address to =
listen_address = 'localhost,172.17.0.1,172.18.0.1'
# save and exit

nano pg_hba.conf
#scroll down and get to hosts the add
# In Local unix line
local    all             all             172.18.0.0/16            scram-sha-256
#In hosts line
host    all             all             172.18.0.0/16            scram-sha-256
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             172.17.0.0/16            scram-sha-256
# save anexit

sudo systemctl restart postgresql


#EXTRAS
pip3 install psycopg2 #MAKE PYTHON ACCESS postgresql

# WIPE ALL TABELS FROM PSQL
sudo -u postgres psql lenicletestdb -c "DO \$\$ DECLARE r RECORD; BEGIN FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.tablename) || ' CASCADE'; END LOOP; END \$\$;"
